# Generated by Django 2.2.28 on 2023-01-18 09:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=64)),
                ('number_of_items', models.PositiveIntegerField()),
                ('required', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurants.AddOn')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sku_number', models.CharField(blank=True, max_length=255)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='dishes/images')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='dishes/images')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='dishes/images')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='restaurants.Restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='addon',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='restaurants.Dish'),
        ),
    ]
