# Generated by Django 2.2.28 on 2023-02-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20230118_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
