# Generated by Django 3.0 on 2023-04-25 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0008_2_5'),
        ('restaurants', '0003_restaurant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='connect_account',
            field=models.ForeignKey(blank=True, help_text="The Restaurant owner's Stripe Account object, if it exists", null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.Account'),
        ),
    ]
