# Generated by Django 3.0 on 2023-07-21 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_dish_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
    ]
