# Generated by Django 3.0 on 2023-08-14 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_auto_20230721_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='category',
        ),
    ]
