# Generated by Django 3.0 on 2023-08-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_remove_dish_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
