# Generated by Django 3.0 on 2023-05-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderdishaddon_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('In Progress', 'In Progress'), ('Driver Assigned', 'Driver Assigned'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered')], default='Unpaid', max_length=32),
        ),
    ]
