# Generated by Django 3.0 on 2023-05-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20230505_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='driver_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
