# Generated by Django 3.0 on 2023-06-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_driver_assigned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cashback_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='order',
            name='taxes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
