# Generated by Django 3.0 on 2023-06-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20230607_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_charge_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_charge_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='driver_payout',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant_payout',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
