# Generated by Django 3.0 on 2023-05-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/cars'),
        ),
    ]
