# Generated by Django 3.0 on 2023-07-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_auto_20230630_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="The Driver's earnings", max_digits=10),
        ),
    ]
