# Generated by Django 3.0 on 2023-04-25 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0008_2_5'),
        ('customers', '0002_customeraddress_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='stripe_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.Customer'),
        ),
    ]
