# Generated by Django 3.0 on 2023-06-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_stripe_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cashback',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
