# Generated by Django 3.0 on 2023-06-07 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0008_2_5'),
        ('payments', '0002_auto_20230607_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='customer_charge',
        ),
        migrations.AddField(
            model_name='payment',
            name='customer_payment_intent',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.PaymentIntent'),
        ),
    ]
