# Generated by Django 3.0 on 2023-06-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230118_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='flagged_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
