# Generated by Django 3.0 on 2023-07-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230628_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activated_profile',
            field=models.BooleanField(default=False),
        ),
    ]
